<!-- Menu -->
<nav class="global">
    <ul>
        <li><a href="index.php" class="btn">Index</a></li>
        <li><a href="product.php" class="btn">Meals</a></li>
        <li><a href="enquire.php" class="btn">Enquire</a></li>
        <li><a href="about.php" class="btn">About Me</a></li>
        <li><a href="enhancements.php" class="btn">Enhancements</a></li>
        <li><a href="enhancements2.php" class="btn">Enhancements2</a></li>
        <li><a href="enhancements3.php" class="btn">Enhancements3</a></li>
        <li><a href="manager.php" class="btn">Manager</a></li>
    </ul>
</nav>
